export const data = {
  center: {
    1: [
      {
        name: "טיול באגמון פולג",
        id: "c11",
        rating: 4.5,
        price: "free",
        time: [2, 2],
        description: `מחצבת כורכר נטושה שמלאה במי תהום וסביבה שביל הליכה מעגלי ומסודר`,
        location: [32.25770715615067, 34.84857279504982],
        workingHours: "always",
        phone: "",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group"],
        image: "center/poleg.png",
      },
      {
        name: `גן לאומי חוף שרון`,
        id: "c12",
        rating: 5,
        price: "free",
        time: [2, 2],
        description: `צוקי כורכר מדהימים על קו החוף, בהם עובר מסלול מעגלי`,
        location: [32.220646845451014, 34.816815238524505],
        workingHours: "always",
        phone: "",
        parking: true,
        handicap: false,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature"],
        for: ["couple", "family"],
        image: "center/hof-hasharon.png",
      },
      {
        name: `גן בוטני יער אילנות`,
        id: "c13",
        rating: 5,
        price: "free",
        time: [2, 2],
        description: `יער גדול המשמש בית למאות סוגי עצים מכל העולם`,
        location: [32.292579200225, 34.899573773764054],
        workingHours: ["08:00", "17:00"],
        phone: "1800-350-550",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "family"],
        image: "center/botani-ilanot.png",
      },
    ],
    2: [
      {
        name: "טיול בשמורת בני ציון",
        id: "c21",
        rating: 4.5,
        price: "free",
        time: [2, 2],
        description: "שתי גבעות כורכר שופעות פריחה משתנה",
        location: [32.22300461431696, 34.85651317376591],
        workingHours: "always",
        phone: "",
        parking: false,
        handicap: false,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature"],
        for: ["couple", "family"],
        image: "center/zion.png",
      },
      {
        name: "גן אפולוניה",
        id: "c22",
        rating: 4.5,
        price: [11, 28],
        time: [2, 3],
        description: `אתר ארכיאולוגי מהמאה השישית לפני הספירה, עם שרידי עיר קדומה ומבצר צלבני עתיק`,
        location: [32.194187192088556, 34.80799648546277],
        workingHours: "always",
        phone: "09-9550929",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["history", "nature"],
        for: ["couple", "family", "group", "alone"],
        image: "center/apolonia.png",
      },
      {
        name: `מרכז המבקרים יער אילנות`,
        id: "c23",
        rating: 5,
        price: [10, 18],
        time: [2, 2],
        description: ` מרכז מבקרים חדשני, המוקדש כולו ליצירה המופלאה של הטבע – עצים, יער וסביבה, משלב את הטכנולוגיות החדישות ביותר בתחום, ומציע למבקרים בו חוויה מיוחדת במינה.`,
        location: [32.220646845451014, 34.816815238524505],
        workingHours: "always",
        phone: "",
        parking: true,
        handicap: false,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature"],
        for: ["couple", "family"],
        image: "center/mevakrim.jpeg",
      },
    ],
    3: [
      {
        name: "פארמה קולטורה",
        id: "c31",
        rating: 4,
        price: [95, 195],
        time: [1, 1],
        description: "חווה אורגנית המציעה חנות לרכישת ירקות שנקטפו ישר מהשדה",
        location: [32.21869207830098, 34.86571147376603],
        workingHours: "always",
        phone: "09-8302311",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food", "culture"],
        for: "all",
        image: "center/pharma-kultura.png",
      },

      {
        name: `לגעת בטבע`,
        id: "c32",
        rating: 4,
        price: [20, 40],
        time: [1, 1],
        description: `מרכז מבקרים לתיירות חקלאית ופינת חי`,
        location: [32.132827988631504, 34.8234309737685],
        workingHours: "10:00 - 14:00",
        phone: "052-66׳20253",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food", "culture"],
        for: "all",
        image: "center/gilboa-bateva.png",
      },
      {
        name: `קטיף תותים בקיבוץ משמר השרון`,
        id: "c33",
        rating: 4,
        price: [25, 25],
        time: [1, 1],
        description: "חווה אורגנית המציעה חנות לרכישת ירקות שנקטפו ישר מהשדה",
        location: [32.21869207830098, 34.86571147376603],
        workingHours: "always",
        phone: "09-8974800",
        parking: true,
        handicap: true,
        seasons: ["winter", "fall"],
        level: 0,
        tags: ["food", "nature"],
        for: "all",
        image: "center/sadot-katif.png",
      },
    ],
    4: [
      {
        name: "סאן קפה",
        id: "c41",
        rating: 4,
        time: [1, 1],
        location: [32.21869207830098, 34.86571147376603],
        workingHours: "always",
        phone: "09-8302311",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["kids", "nature"],
        for: "all",
        image: "center/sun-caffe.png",
      },
      {
        name: `קפה פרסה`,
        id: "c42",
        rating: 4,
        time: [1, 1],
        location: [32.21869207830098, 34.86571147376603],
        workingHours: ["9:00", "18:00"],
        phone: "052-6033212",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food"],
        for: "all",
        image: "center/parsa-caffe.png",
      },
      {
        name: `ביסטרו גרציא`,
        id: "c43",
        rating: 4,
        price: [95, 195],
        time: [1, 1],
        location: [32.21869207830098, 34.86571147376603],
        workingHours: "always",
        phone: "09-8943942",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food"],
        for: "all",
        image: "center/gracia-caffe.png",
      },
    ],
  },
  north: {
    1: [
      {
        name: "הג׳ובה הגדולה",
        id: "n11",
        rating: 4,
        price: "free",
        time: [1.5, 2],
        description: `בור וולקני טבעי ועצום בעומק 60 מטרים ובקוטר 200 מטרים - תופעת טבע מרתקת שסביבה מסלול הליכה מקסים`,
        location: [33.20870438233507, 35.733562306248764],
        workingHours: "always",
        phone: "",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group"],
        image: "north/big-job.png",
      },
      {
        name: "עגלת קפה בית לחם הגלילית",
        id: "n12",
        rating: 5,
        price: "free",
        time: [0.5, 1],
        description: `בור וולקני טבעי ועצום בעומק 60 מטרים ובקוטר 200 מטרים - תופעת טבע מרתקת שסביבה מסלול הליכה מקסים`,
        location: [32.73660333392895, 35.1903773],
        workingHours: ["08:00", "20:00"],
        phone: "054-774-3306",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food"],
        for: ["couple", "group", "family"],
        image: "north/agalat.png",
      },
      {
        name: "עין אביאל",
        id: "n13",
        rating: 5,
        price: "free",
        time: [4, 4],
        description: `יובל של נחל התנינים ניתן ללכת במיםֿ יש אפשרות לשבת במערה מאחורי מפל`,
        workingHours: `always`,
        phone: "054-774-3306",
        parking: true,
        handicap: false,
        seasons: ["spring", "summer", "fall"],
        level: 0,
        tags: ["nature"],
        for: ["couple", "group", "family"],
        image: "north/aviel.png",
      },
    ],
    2: [
      {
        name: `פארק עורבים`,
        id: "n21",
        rating: 5,
        price: "free",
        time: [2, 2],
        description: `.שבילי הליכה שמובילים לארמון האמיר, מתקני פיקנק, גשרוני עץ ושבילי בזלת`,
        location: [33.14041526289825, 35.733329744415116],
        workingHours: ["9:00", "18:00"],
        phone: "",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature"],
        for: ["couple", "family"],
        image: "north/orvim.png",
      },
      {
        name: "שביל פרות החלב",
        id: "n22",
        rating: 5,
        price: [42],
        time: [0.5, 1],
        description: `סיור ברפת, ליטוף והאכלה של חיות`,
        location: [32.7388316498659, 35.19333353096032],
        workingHours: ["10:00", "16:00"],
        phone: "052-327-5682",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["food", "kids"],
        for: ["couple", "group", "family"],
        image: "north/cows.png",
      },
      {
        name: `עגלת קפה ציפורה`,
        id: "n23",
        rating: 5,
        price: "free",
        time: [1, 2],
        description:
          "עגלת קפה ונישנושים בסמוך לנחל לתנינים, במקום צל ופינות ישיבה",
        location: [32.535859143344509, 34.98833119047584],
        workingHours: ["08:00", "13:00"],
        phone: "054-203-2092",
        parking: true,
        handicap: true,
        seasons: ["spring", "winter", "summer", "fall"],
        level: 0,
        tags: ["food"],
        for: ["couple", "group", "family"],
        image: "north/cafe-zipora.png",
      },
    ],
    3: [
      {
        name: `יער איילים`,
        id: "n31",
        rating: 5,
        price: "free",
        time: [1, 2],
        description: `.מתחם אטרקציות שמציע פינת חי וליטוף שעשועי ספורט ומסלול אתגרי`,
        location: [33.19217790386731, 35.750970502574255],
        workingHours: ["9:00", "18:00"],
        phone: "0545446202",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature", "kids"],
        for: ["family"],
        image: "north/ayalim.png",
      },
      {
        name: "שמורת אלוני אבא",
        id: "n32",
        rating: 5,
        price: [42],
        time: [1, 2],
        description: "יער עצי אלון התבור",
        location: [32.7342404119228, 35.171458428905765],
        workingHours: ["8:00", "17:00"],
        phone: "04-993-0095",
        parking: true,
        handicap: false,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group", "family"],
        image: "north/alonei.png",
      },
      {
        name: `פארק אלונה`,
        id: "n33",
        rating: 5,
        price: "free",
        time: [1, 2],
        description: `הליכה בנקבת מים עתיקה מימי הרומאים מתחת לאדמה`,
        location: [32.5550336790215, 35.00616700699978],
        workingHours: ["09:00", "15:00"],
        phone: "04-638-43-22",
        parking: true,
        handicap: true,
        seasons: ["spring", "winter", "summer", "fall"],
        level: 2,
        tags: ["historic", "water"],
        for: ["couple", "group", "family"],
        image: "north/alona.png",
      },
    ],
    4: [
      {
        name: `מתחם במבוק פארק`,
        id: "n41",
        rating: 4,
        price: [40, 100],
        time: [1, 2],
        description: `ביקור במתחם במבוק פארק ובית הקפה הצף בברכת רם`,
        location: [33.19217790386731, 35.750970502574255],
        workingHours: ["9:00", "18:00"],
        phone: "052-2545441",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 2,
        tags: ["nature", "food", "sports"],
        for: ["family"],
        image: "north/birkat.png",
      },
      {
        name: "אסאדו בר",
        id: "n42",
        rating: 4,
        time: [1, 2],
        location: [32.32721838084580995, 35.14140348465952],
        workingHours: ["12:00", "10:00"],
        phone: "054-420-0291",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group", "family"],
        image: "north/asado-bar.png",
      },

      {
        name: "ההר העגול",
        id: "n43",
        rating: 4,
        time: [1, 2],
        description: `טיול טבע קצקצר, בראש ההר אנדטרת זיכרון לגדוד 890`,
        location: [32.56470372168204, 35.031675827348685],
        workingHours: "always",
        phone: "054-420-0291",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature", "picnic"],
        for: ["couple", "group", "family"],
        image: "north/agol.jpeg",
      },
    ],
  },
  south: {
    1: [
      {
        name: "גן לאומי עין עבדת",
        id: "s11",
        rating: 4.5,
        price: "free",
        time: [1.5, 3],
        description: `מסלול מדהים וקליל בנוף מדברי. קילומטר וחצי של מצוקים, מעיינות, המון יעלים.`,
        location: [30.83287769741197, 34.77120969911249],
        workingHours: ["08:00", "17:00"],
        phone: "086555684",
        parking: true,
        handicap: false,
        seasons: ["spring", "summer", "fall"],
        level: 3,
        tags: ["nature"],
        for: ["couple", "group"],
        image: "south/ovdat.png",
      },
      {
        name: "חוות קורנמל",
        id: "s12",
        rating: 5,
        price: "free",
        time: [0.5, 1],
        description: `חוות עיזים על רקע מדברי, מקום פסטורלי המגיש אוכל מגבינות עיזים.`,
        location: [30.973048803690695, 34.77630922187714],
        workingHours: ["10:00", "17:00"],
        phone: "08-6555-140",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],

        tags: ["food"],
        for: ["couple", "group", "family"],
        image: "south/kornamel.png",
      },
      {
        name: "שדה בוקר",
        id: "n13",
        rating: 5,
        price: [20, 40],
        time: [1, 2],
        location: [30.874011695663103, 34.79441762052204],
        description: `ההתיישבות בשדה בוקר החלה בתצורה של חווה חקלאית בנגב. הרעיון להקמת חווה באזור זה הבשיל אצל מתנדב אמריקאי בשם ג'סי אשר לחם בארץ במסגרת מלחמת העצמאות `,
        workingHours: `always`,
        phone: "054-774-3306",
        parking: true,
        handicap: false,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["historic"],
        for: ["couple", "group", "family"],
        image: "south/boker.png",
      },
    ],
    2: [
      {
        name: `כנעניה מדרשת עין בוקר`,
        id: "n21",
        rating: 5,
        price: "free",
        time: [2, 2],
        description: `מעדנייה ובית קפה איכותי באמצע המדבר`,
        location: [30.85641147112883, 34.783481832770235],
        workingHours: ["8:00", "15:00"],
        phone: "0547689464",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 0,
        tags: ["food"],
        for: ["couple", "family"],
        image: "south/knanya.jpeg",
      },
      {
        name: "ספארי מדרשת בן גוריון",
        id: "n22",
        rating: 4,
        price: [42],
        time: [0.5, 1],
        description: `מוזיאון טבע ונחשייה`,
        location: [30.849478602608713, 34.780976232052694],
        workingHours: ["10:00", "16:00"],
        phone: "054-5343-797",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["meuseum", "kids"],
        for: ["couple", "group", "family"],
        image: "south/nahs.png",
      },
      {
        name: `מצפור גל ליפא`,
        id: "n23",
        rating: 3,
        price: "free",
        time: [1, 2],
        description: "נקודת תצפית מרהיבה על שדה בוקר",
        location: [30.822714197280174, 34.7415071534533],
        workingHours: ["08:00", "13:00"],
        phone: "054-203-2092",
        parking: true,
        handicap: true,
        seasons: ["spring", "winter", "summer", "fall"],
        level: 0,
        tags: ["nature"],
        for: ["couple", "group", "family"],
        image: "south/lifa.jpeg",
      },
    ],
  },
  jerusalem: {
    1: [
      {
        name: "פאר עמק הצביים",
        id: "j21",
        rating: 4.5,
        price: "free",
        time: [1.5, 2],
        description:
          "מקום מקסים לטייל ולערוך פיקניק, מתגוררים בפארק 60 סוגי צביים ומיני ציפורים",
        location: [31.789624287007324, 35.202895873046984],
        workingHours: ["07:00", "19:30"],
        phone: "052-4234454o",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group", "family"],
        image: "jerusalem/bambi.jpeg",
      },
      /* {
        name: `ברבהר`,
        id: "j22",
        rating: 4,
        price: "free",
        time: [1.5, 4],
        description: `מסעדה היושבת על צלע הר עם נוף להרי יהודה. פיצות פסטות ומזון צמחוני`,
        location: [31.7347144044932, 35.07200588839398],
        workingHours: ["10:30", "14:30"],
        phone: "02-9227699",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["food"],
        for: ["family"],
        image: "jerusalem/barbahar.png",
      }, */
      {
        name: "פונדק עין כרם",
        description: `בין מנזרים, ורחובות עתיקים ישנו פונדק המעניק חוויה כפרית עם בשרים ומנות מהים`,
        id: "j23",
        rating: 4,
        time: [1, 1],
        location: [31.76631078513908, 35.16159546838507],
        workingHours: ["09:30", "23:00"],
        phone: "054-2349493",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["food"],
        image: "jerusalem/pundak.png",
      },
      {
        name: "כנסיית יוחנן המטביל בעין כרם",
        description: `כנסיית יוחנן המטביל בירושלים, היא כנסייה יוונית-אורתודוקסית קטנה ברובע הנוצרי. הכנסייה מצויה בדרום הרובע הנוצרי`,
        id: "j23",
        time: [1, 1],
        rating: 4,
        price: "free",
        location: [31.76631078513908, 35.16159546838507],
        workingHours: ["09:30", "23:00"],
        phone: "054-2349493",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["historic"],
        image: "jerusalem/johanan.jpeg",
      },
    ],
    2: [
      {
        name: "אתר לאומי הקסטל",
        id: "j31",
        rating: 4,
        price: "free",
        time: [1.5, 4],
        description: "אתר הנצחה מרשים למלחמת העצמאות",
        location: [31.797560634839204, 35.14209869505379],

        workingHours: ["08:30", "16:30"],
        phone: "077-44356324",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["historic"],
        for: ["couple", "group", "family"],
        image: "jerusalem/castle.png",
      },
      {
        name: `מסעדת רשטא`,
        id: "j32",
        rating: 4,
        price: "free",
        time: [1.5, 4],
        description: `מסעדה מקסימה וטעימה בליבו של כפר עין רפא`,
        location: [31.79210280467242, 35.11632626864],
        workingHours: ["12:30", "23:30"],
        phone: "02-9227699",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["food"],
        for: ["family"],
        image: "jerusalem/rashta.png",
      },

      {
        name: "הגן הבוטני יורשלים",
        id: "j21",
        rating: 4.5,
        price: "free",
        time: [1.5, 4],
        description: `גן בוטני לבילוי משםחתי עם מגוון צמחים מרחבי העולם`,
        location: [31.755414791043354, 35.17357503072207],
        workingHours: ["09:00", "19:00"],
        phone: "055-344-5532",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature", "meseum"],
        for: ["couple", "group", "family"],
        image: "jerusalem/botani.jpeg",
      },
    ],
  },
  yehuda: {
    1: [
      {
        name: "חוות אייל",
        id: "y11",
        rating: 4.5,
        price: "free",
        time: [1, 1.5],
        description: `חווה אקולוגית טיפולית ובית חינוכי לשמירה על הטבע והסביבה`,
        location: [31.665269139458047, 34.9369476883951],
        workingHours: ["10:00", "13:00"],
        phone: "",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring"],
        level: 1,
        tags: [],
        for: ["family"],
        image: "jerusalem/eyal.jpg",
      },
      {
        name: `פיקניק ברמת רחל`,
        id: "y12",
        rating: 4.5,
        price: "",
        time: [1, 1.5],
        description: `פיקניק מפנק בפיסת טבע מרגיעה  בתוך העיר.`,
        location: [31.665269139458047, 34.9369476883951],
        workingHours: ["09:00", "15:00"],
        phone: "052-420-7088",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["food"],
        for: ["couple", "group"],
        image: "jerusalem/rahel.png",
      },
      {
        name: "עין לבן",
        id: "y13",
        rating: 4.5,
        price: "free",
        time: [1, 1.5],
        description: `גריל בשר ארגנטינאי טעיייים מזנון סלטים עשיר מקום קיבוצי קסוםאתר טבע מרהיב ביופיו הכולל טרסות מטופחות ועשירות בעצי בוסתן פורחים בארומה ירושלמית תנ"כית`,
        location: [31.749861622331647, 35.15975281552238],
        workingHours: "always",
        phone: "02-500-5463",
        parking: true,
        handicap: true,
        seasons: ["winter", "spring", "summer", "fall"],
        level: 1,
        tags: ["nature"],
        for: ["couple", "group"],
        image: "jerusalem/lavan.jpg",
      },
    ],
  },
  2: [
    {
      name: "חורבת בורגין",
      id: "y21",
      rating: 4.5,
      price: "free",
      time: [2, 3],
      description:
        "מסלול מעגלי חוויתי בין שרידי ישוב קדום מתקופות שונות. הכולל כניסה למערות רבות ומגוונות הפזורות לאורכו ותצפית נהדרת על השפלה וההר. בחורף ובאביב- פריחה נפלאה.",
      location: [31.63865, 34.96944],
      workingHours: ["07:00", "19:30"],
      phone: "",
      parking: true,
      handicap: true,
      seasons: ["winter", "spring"],
      level: 1,
      tags: ["historic", "nature"],
      for: ["couple", "group", "family"],
      image: "jerusalem/caves.jpg",
    },
    {
      name: "יקב רוגלית",
      id: "y12",
      rating: 4.5,
      price: "",
      time: [1, 1.5],
      description: `היקב מיצר יין מענבים שנבצרים בבציר ידני ומוקפד בשעות הבוקר המוקדמות. היקב נמצא במרתף שניבנה בשנות ה 50 בחצר הבית הצופה אל נוף עמק האלה הפסטורלי המכונה "דרך היין" ומספק חוויה כפרית יחודית ומשפחתית .`,
      location: [31.672207571249366, 35.00243227387962],
      workingHours: ["10:30", "15:00"],
      phone: "052-420-7088",
      parking: true,
      handicap: true,
      seasons: ["winter", "spring", "summer", "fall"],
      level: 1,
      tags: ["alcohol"],
      for: ["couple", "group"],
      image: "jerusalem/rogalit.png",
    },
    {
      name: "נפלאות הגריל הארגנטינאי",
      id: "y13",
      rating: 4.5,
      price: "",
      time: [1, 1.5],
      description: `גריל בשר ארגנטינאי טעיייים מזנון סלטים עשיר מקום קיבוצי קסום`,
      location: [31.68560397614781, 34.98223612351948],
      workingHours: ["12:00", "18:00"],
      phone: "054-5987231",
      parking: true,
      handicap: true,
      seasons: ["winter", "spring", "summer", "fall"],
      level: 1,
      tags: ["food"],
      for: ["couple", "group"],
      image: "jerusalem/grill.jpg",
    },
  ],
};
